### PR TITLE
Fix test runner events parsing and align with node 20.7.0

### LINKED ISSUE #82: Parsing results do not reflect test results
This behaviour can be reproduced parsing sources containing some failing tests.

For example having 4 tests with 3 of them passing and 1 failing the parser reports 1 passed and 1 failed.

Linked to: https://github.com/nearform/node-test-github-reporter/issues/98

### PR DESCRIPTION
**Pull request by msebastianb**
This is a list of things changed on node test runner since the latest release:

- File string format is changed now it returns the url scheme too then in our case has _file:_ in front of the path
- generatedMessage must be true in that case because the message is automatically generated, if a custom message is passed as the third parameter of for example strictEquale function the variable will be false
- On subtestFailed failure type now the cause is "<_number_> subtest failed" instead of an empty object
- On testTimeoutFailure failure type now the cause is "test timed out after <_timeout ms_>" instead of an empty object

**Suggested solution:**

- Parse the file url and return it as expected
- Align the expected tests results with node 20.7.0

Closes #82

### CODE REVIEW

File: parse-report.js [hunk 1]
```diff
@@ -27,6 +27,11 @@ export default async function parseReport(source) {
     diagnosticMessage = ''
   }
 
+  // Removes file: form the start of the string
+  function parseFilePath(file) {
+    return file.replace(/^file:/, '')
+  }
```
Comment (simoneb) [inline parse-report.js:33]: q: would it be safer to use the url module here instead of string replacement?

Comment (msebastianb) [reply parse-report.js]: Thanks @simoneb, I've done a safer implementation right now.

**Review by simoneb — APPROVED** [review]
